#!/usr/bin/env python3
"""Write only allowlisted PUBLIC settings. Never copies private bot environment."""
import json
import os
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "public/js/config.js"
KEYS = ["SHARED_SWAPS_URL", "FIREBASE_API_KEY", "TELEGRAM_BOT_NAME",
        "TELEGRAM_OWNER_ID", "TELEGRAM_ADMIN_IDS", "SCHED_NOTIFY_URL"]

def build(path=PATH, env=None):
    env = os.environ if env is None else env
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    result = ["/* Public sched configuration; generated by scripts/build_config.py. */"]
    for key in KEYS:
        match = re.search(r'var\s+' + key + r'\s*=\s*("(?:\\.|[^"\\])*")\s*;', current)
        old = json.loads(match.group(1)) if match else ""
        value = str(env.get(key) or "").strip() or old
        result.append("var " + key + " = " + json.dumps(value, ensure_ascii=False) + ";")
    path.write_text("\n".join(result) + "\n", encoding="utf-8")

if __name__ == "__main__":
    build()
    print("Public sched configuration generated; secret values not displayed.")
